#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"

#include "CMBattleComponent.generated.h"

UENUM(BlueprintType)
enum class ECMPartHitResult : uint8
{
    Invalid,
    Damaged,
    Parried,
    Dead
};

/** Server-authored description of one attack touching this Part. */
USTRUCT(BlueprintType)
struct FCMPartHitPayload
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite)
    TObjectPtr<AActor> Attacker;

    UPROPERTY(BlueprintReadWrite)
    TObjectPtr<AActor> SourceActor;

    UPROPERTY(BlueprintReadWrite, meta = (ClampMin = "0.0"))
    float Damage = 0.0f;

    UPROPERTY(BlueprintReadWrite)
    FVector ImpactPoint = FVector::ZeroVector;

    UPROPERTY(BlueprintReadWrite)
    FVector ImpactNormal = FVector::ZeroVector;

    /** Reuse the same valid ID for every trace generated by one attack. */
    UPROPERTY(BlueprintReadWrite)
    FGuid AttackId;
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(
    FCMPartHitResolvedSignature,
    ECMPartHitResult,
    Result,
    FCMPartHitPayload,
    HitPayload
);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(
    FCMPartParrySucceededSignature,
    FCMPartHitPayload,
    HitPayload
);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(
    FCMParryWindowChangedSignature,
    bool,
    bIsActive
);

/**
 * Server-authoritative combat state owned by one Part Actor.
 *
 * It resolves duplicate-hit filtering and parry state, then forwards accepted
 * damage to the owning Part Actor. HP, input, GAS costs, animation, slot
 * detachment, and attacker reactions stay outside this component.
 */
UCLASS(ClassGroup = (Chimera), meta = (BlueprintSpawnableComponent))
class CHIMERA_API UCMBattleComponent : public UActorComponent
{
    GENERATED_BODY()

public:
    UCMBattleComponent();

    virtual void GetLifetimeReplicatedProps(
        TArray<FLifetimeProperty>& OutLifetimeProps
    ) const override;

    UFUNCTION(BlueprintCallable, BlueprintAuthorityOnly,
        Category = "Chimera|Battle")
    ECMPartHitResult ResolveHit(const FCMPartHitPayload& HitPayload);

    /** Opens a server-timed parry window that remains active for its duration. */
    UFUNCTION(BlueprintCallable, BlueprintAuthorityOnly,
        Category = "Chimera|Battle")
    bool BeginParryWindow(float Duration);

    UFUNCTION(BlueprintCallable, BlueprintAuthorityOnly,
        Category = "Chimera|Battle")
    void EndParryWindow();

    UFUNCTION(BlueprintPure, Category = "Chimera|Battle")
    bool IsParryWindowActive() const;

    /** Server-only result notification. Presentation can later bridge this to cues. */
    UPROPERTY(BlueprintAssignable, Category = "Chimera|Battle")
    FCMPartHitResolvedSignature OnHitResolved;

    UPROPERTY(BlueprintAssignable, Category = "Chimera|Battle")
    FCMPartParrySucceededSignature OnParrySucceeded;

    UPROPERTY(BlueprintAssignable, Category = "Chimera|Battle")
    FCMParryWindowChangedSignature OnParryWindowChanged;

protected:
    virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

private:
    UFUNCTION()
    void OnRep_ParryWindowActive();

    bool WasAttackAlreadyResolved(const FGuid& AttackId) const;
    void RememberResolvedAttack(const FGuid& AttackId);

    UPROPERTY(ReplicatedUsing = OnRep_ParryWindowActive,
        VisibleInstanceOnly, BlueprintReadOnly, Category = "Chimera|Battle",
        meta = (AllowPrivateAccess = "true"))
    bool bParryWindowActive = false;

    TArray<FGuid> RecentResolvedAttackIds;
    FTimerHandle ParryWindowTimerHandle;
};
