#pragma once

#include "NativeGameplayTags.h"

namespace CMSoundTags
{
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BGM_Menu);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BGM_Stage_Stage01);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BGM_Result_Victory);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BGM_Result_Defeat);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BGM_Ending);

    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Body_Footstep);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Body_BloodDragLoop);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Body_Hit);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Body_Death);

    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Part_Pickup);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Part_Attach);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Part_Detach);

    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI_Aggressive_TargetSpotted);

    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_Button_Press);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_PressurePlate_WeightChanged);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_Obstacle_RotatingBlade_ActiveLoop);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_Obstacle_Fan_ActiveLoop);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_Obstacle_Laser_On);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_Obstacle_Laser_Off);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_Obstacle_Laser_ActiveLoop);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_Obstacle_PushBox_MoveLoop);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_Lever_MoveLoop);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_Lever_Settle);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_VisionStone_OnLoop);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_VisionStone_OffLoop);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_Door_Open);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_Door_Close);

    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Click);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Confirm);
    CMSOUND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Cancel);
}
