#pragma once

#include "NativeGameplayTags.h"

namespace CMSoundTags
{
    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BGM_Menu);
    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BGM_Stage_Stage01);
    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BGM_Result_Victory);
    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BGM_Result_Defeat);
    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BGM_Ending);

    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Body_Footstep);
    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Body_Hit);
    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Body_Death);

    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Part_Pickup);
    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Part_Attach);
    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Part_Detach);

    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_Button_Press);
    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_Door_Open);
    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stage_Door_Close);

    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Click);
    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Confirm);
    CHIMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Cancel);
}
