#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"

namespace UITags
{
	// UI Layer
	NKMUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_HUD);
	NKMUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Menu);
	NKMUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Modal);

	// UI Extension point
	// HUD
	NKMUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Extension_HUD_Full);
	NKMUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Extension_HUD_BottomLeft);
	NKMUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Extension_HUD_BottomRight);
	NKMUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Extension_HUD_BottomCenter);
	NKMUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Extension_HUD_MiddleLeft);
	NKMUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Extension_HUD_MiddleRight);
	NKMUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Extension_HUD_CenterRight);
	NKMUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Extension_HUD_MiddleCenter);
	NKMUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Extension_HUD_TopLeft);
	NKMUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Extension_HUD_TopRight);
	NKMUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Extension_HUD_TopCenter);
	NKMUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Extension_MainMenu_MiddleCenter);
}
